# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-test',
                'doc_host': 'https://levelalphaone.github.io',
                'git_url': 'https://github.com/levelalphaone/nbdev-test',
                'lib_path': 'nbdev_test'},
  'syms': { 'nbdev_test.core': { 'nbdev_test.core.add': ('core.html#add', 'nbdev_test/core.py'),
                                 'nbdev_test.core.sample_main': ('core.html#sample_main', 'nbdev_test/core.py')},
            'nbdev_test.core_2': { 'nbdev_test.core_2.add': ('second.html#add', 'nbdev_test/core_2.py'),
                                   'nbdev_test.core_2.sample_main': ('second.html#sample_main', 'nbdev_test/core_2.py')}}}
