# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['sample_main', 'add']

# %% ../nbs/00_core.ipynb 3
def sample_main(name:str):
    "This is a sample function from the first module"
    
    print(f"Hello {name}!!")

# %% ../nbs/00_core.ipynb 4
def add(a:int, b:int):
    "Function to add two numbers"
    
    return a+b
