# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_second.ipynb.

# %% auto 0
__all__ = ['sample_main', 'add']

# %% ../nbs/02_second.ipynb 3
def sample_main(name:str):
    "This is a sample function from the first module"
    
    print(f"Hello {name}!!")

# %% ../nbs/02_second.ipynb 4
def add(a:int, b:int):
    "Function to add two numbers"
    
    print(f"Sum of two numbers: {a+b}")
    return a+b
